name: matchly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- UI & Design System ---
  google_fonts: ^6.1.0        # Tipografia customizada desportiva
  phosphoricons_flutter: ^1.0.0    # Ícones modernos e finos
  shimmer: ^3.0.0             # Skeleton Loaders
  flutter_animate: ^4.5.0     # Animações e micro-interações fluidas

  # --- Cache & Imagens ---
  cached_network_image: ^3.3.1 # Cache de imagens dos clubes/ligas com fade
  flutter_svg: ^2.0.10+1      # Suporte para logótipos vetoriais

  # --- Utilidades & Estado ---
  intl: ^0.20.2               # Formatação de datas/horas dos jogos

  # --- Data, Env, API & Storage ---
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
      - .env
