// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbjyJdU28CRUBGEH5QyKjPfBScovTGgjQ',
    appId: '1:148385810588:web:992b12fbef7e9b259f4559',
    messagingSenderId: '148385810588',
    projectId: 'matchly-live',
    authDomain: 'matchly-live.firebaseapp.com',
    storageBucket: 'matchly-live.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rLe-k5vK2_8wS5MsRyJ54AtyzGEuLc8',
    appId: '1:148385810588:android:8a53000e7f355d709f4559',
    messagingSenderId: '148385810588',
    projectId: 'matchly-live',
    storageBucket: 'matchly-live.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6AEqd0DeqZrSxYqn1WDbbay0vYoCgNas',
    appId: '1:148385810588:ios:46e18662307cc8e89f4559',
    messagingSenderId: '148385810588',
    projectId: 'matchly-live',
    storageBucket: 'matchly-live.firebasestorage.app',
    iosBundleId: 'com.example.matchly',
  );
}
